services:
  # Backend API service
  - type: web
    name: heart-failure-prediction-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: PORT
        value: 10000

  # Frontend static site
  - type: web
    name: heart-failure-prediction-frontend
    env: static
    buildCommand: echo "Static site, no build needed"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 